apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: morislex-rag

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - ui-deployment.yaml
  - pipeline-deployment.yaml
  - retrieval-deployment.yaml
  - networkpolicy.yaml
  - ollama-deployment.yaml
